### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [GustavoASantos/Noti#15]
https://hosted.weblate.org/projects/noti-progress-bar/#information says
GPLv3-only, but I am thinking you wanted
GPLv3-or-later?

Can be changed in https://hosted.weblate.org/settings/noti-progress-bar/strings/

**Comment by GustavoASantos** [comment]
Thanks for the heads up but I meant GPLv3-only, just like the code. Were you thinking of any reason to go for the GPLv3-or-later?

**Comment by comradekingu** [comment]
The code doesn't say one way or the other specifically what it is.
"or-later" allows for greater flexibility in moving to for example AGPLv3+, and I suppose a GPLv4 in the future.
That also means other projects can make use of it more easily.

**Comment by GustavoASantos** [comment]
Got it, I'll change it. Thanks for helping translate Noti!
