### ISSUE TITLE
Play Store Version is 1.7 but in this Github repo Its version is still 1.6

### ISSUE THREAD

**Issue by SagXD** [GustavoASantos/Noti#27]
![image](https://github.com/GustavoASantos/Noti/assets/95903022/8d330616-1184-482a-8eca-077e504fee61)
As You can see screenshot of Play Store or You update source after updating Play Store Version? Thank You

**Comment by SagXD** [comment]
@GustavoASantos Or just I have to bump the the version in build.gradle?

**Comment by GustavoASantos** [comment]
> Or just I have to bump the the version in build.gradle?

No, I haven't made it public yet but I will

**Comment by RikudouSage** [comment]
You're in breach of your own license, GPL states that anyone who has access to the app also must have access to the source code. So unless you changed the the license for 1.7, you are obligated to release the source codes at least to everyone who bought the app.

**Comment by SagXD** [comment]
> > Or just I have to bump the the version in build.gradle?
> 
> No, I haven't made it public yet but I will

OK Thanks Just keep the source updated. Maybe, I will buy this cool app to support development. ;)
