### ISSUE TITLE
Only available on Play Store

### ISSUE THREAD

**Issue by Optissimum** [GustavoASantos/Noti#28]
It would be goods to release the apks here so they can be accessed with Obtanium, or on alternative app stores like F-Droid, so that people who don't have Play Store access or computer access can install it.

**Comment by GustavoASantos** [comment]
Sorry, that's not something I plan on doing. Everyone's free to build it from source, but I also ask that you please don't share the apk file online

**Comment by ORIOLESFan02** [comment]
> Sorry, that's not something I plan on doing. Everyone's free to build it from source, but I also ask that you please don't share the apk file online

Boo

**Comment by ORIOLESFan02** [comment]
> but I also ask that you please don't share the apk file online

Ironic since it's GPL3 which states the following:
`Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software`
and
`This program is free software: you can redistribute it...`

**Comment by GustavoASantos** [comment]
I know it does. It's just a request I make so I don't get a ton of emails from people installing it from outside the Play Store, I have trouble offering support to everyone from the Play Store as it is

**Comment by the-dunce** [comment]
Well it sounds like a more community-driven support model like people helping each other via github issues/discussions would be a benefit to you too then...

Just throwing out that I would be interested in trying this, but not interested enough to further enrich Google or bother compiling a currently outdated version from source.
