### ISSUE TITLE
My current app stop responding when there's a progress going on

### ISSUE THREAD

**Issue by NikunjKhangwal** [GustavoASantos/Noti#38]
I updated noti to version 1.8 today. Suddenly whenever a progress is going on in notification bar (like music, download etc) my foreground app (let say I'm using play store to download something) freezes. I can't scroll or click any button but the app is still working. Initially i thought this was happening because of system webview since webview had multiple cases of freezing apps in past but even the apps that don't utilise webview were freezing. Until i found out it was happening because of noti. I turned off the background process and force stopped the app and suddenly all of the apps started working again. I re-launched noti to confirm and i was back to freezes. I purchased the app from play store so i can't downgrade to previous version. Hopefully you'll find the problem and release a fix soon. 🙏🏼

**Comment by GustavoASantos** [comment]
What phone do you have and what android version is it running? Also did you give noti accessibility permission?

**Comment by NikunjKhangwal** [comment]
Redmi 9 Global, Android 12, MIUI 13

Yes accessibility permission is granted. Weird thing is it was working fine last version in same phone, even without accessibility service. It just started to happen in new one.

**Comment by GustavoASantos** [comment]
Does the same thing happen if you disable the accessibility service?

**Comment by NikunjKhangwal** [comment]
Yes

**Comment by GustavoASantos** [comment]
Another question, do you have the show progress bar in lock screen option enabled?

**Comment by NikunjKhangwal** [comment]
No, it's disabled

**Comment by NikunjKhangwal** [comment]
From my guess i don’t think its an Accessibility problem. As i mentioned it was working fine without accessibility service before anyway.

**Comment by GustavoASantos** [comment]
> No, it's disabled

I believe if you enable that option it should work correctly, can you confirm it?

**Comment by NikunjKhangwal** [comment]
Sorry i can't, I uninstalled the app because of the issues and my play store is showing only 1.7 now.

**Comment by GustavoASantos** [comment]
No problem, I believe I have found the problem, a fix will be available shortly. Thanks for reporting this!

**Comment by GustavoASantos** [comment]
The fix is live on the Play Store, let me know if it works for you

**Comment by NikunjKhangwal** [comment]
Seems to be working now, I'll report if i notice something. Thanks a lot for the quick fix and keep up the nice work. 🙌🏼
