### ISSUE TITLE
Timer countdown

### ISSUE THREAD

**Issue by D3NIS4O** [GustavoASantos/Noti#6]
If it's possible and if you want, you can make it show how much time is left on the timer

**Comment by GustavoASantos** [comment]
Thanks for the suggestion! I'll look into it but I don't know if it's possible to have a solution that fits all clock apps

**Comment by Killmonger007** [comment]
> Thanks for the suggestion! I'll look into it but I don't know if it's possible to have a solution that fits all clock apps

There is an app called Dynamic Spot that has a similar feature, so it is possible, but I don't know how yet.

**Comment by GustavoASantos** [comment]
> There is an app called Dynamic Spot that has a similar feature, so it is possible, but I don't know how yet.

The problem is knowing the total duration of the timer. To show accurate progress we need more than just the current time left. I haven't had the time to look into it yet but I'll give you a proper answer soon™️
