### ISSUE TITLE
KEEPS DOWNLOADING WHEN NOTHING IS

### ISSUE THREAD

**Issue by SKU003** [GustavoASantos/Noti#61]
Hi, after a download instead of stopping it keeps on loading and loading until I have to force stop the app, and it still when I open it back it still does it and nothing is installing or downloading. 
So I've just put it on the "no progress bar" but that's not why I installed the Noti Progress bar. 

At first, it was okay then it just started to bug on me. 
Also, I can't seem to find it on apps that shouldn't be sleeping so it doesn't close, you know so my phone ignores it. 

https://github.com/GustavoASantos/Noti/assets/117542049/41ce73fa-c608-4b82-882e-c8dd6b67b9eb

**Comment by GustavoASantos** [comment]
Hi! What you're seeing seems to be the media progress bar for Samsung Internet. To stop this from showing, you can either disable the media progress bar or disable Noti for Samsung Internet in the per-app settings
