### ISSUE TITLE
crash at per app setting

### ISSUE THREAD

**Issue by Killmonger007** [GustavoASantos/Noti#7]
I built the app using source code in Android Studio. However, the app crashes when I select colors in the 'per app settings' menu.

https://github.com/GustavoASantos/Noti/assets/65183354/4e9df800-ae0f-4ccb-9c8f-c73ebf4716d0

**Comment by GustavoASantos** [comment]
What android version are you using?

**Comment by GustavoASantos** [comment]
Should be fixed now but please confirm it

**Comment by Killmonger007** [comment]
> @Killmonger007 What android version are you using?

android 11

**Comment by Killmonger007** [comment]
> Should be fixed now but please confirm it

fixed 👍
