### ISSUE TITLE
Noti Randomly stops working

### ISSUE THREAD

**Issue by AdriandeLima** [GustavoASantos/Noti#71]
I'm using the latest version of the app (1.9), on a Pixel 6, A14.

I've found that randomly the progress bar will dissapear and stop showing up (easily seen when listening to music), and when I poke around, it's usually something to do with the accessibility permission. Sometimes turning it off and on again fixes the issue, other times I need to force stop the app, which seems to force remove the accessibility permission, which I then need to re-enable, all of which is a process it would be nice to not have to do. I used to use another app that constantly had issues with the accessibility permission, so I'm not sure if this is a Noti issue, or something to do with how android handles accessibility, but it would be great if there was a way to work around this. I love the app, but it's quite frustrating when it randomly stops working every couple of weeks or so, it'd be great to be able to set and forget it.

**Comment by GustavoASantos** [comment]
I'll try to look into it

**Comment by GustavoASantos** [comment]
Should be fixed. Let me know if it happens again
